### ISSUE TITLE
SUGGESTION Option to disable skins

### ISSUE THREAD

**Issue by SOMSTATE** [MeGaGiGaGon/SurvivorEnemyAndSkillCustomizer#1]
An option for disabling skins would be nice to disable things that go against the Risk of Rain 2 aesthetic, as commonly found in some survivors, skins, or when using the Hopoo Face Lift mods.

**Comment by MeGaGiGaGon** [comment]
Interesting idea. If I do end up adding it, it will take a while, since interacting with the skin system is more complex than what I am currently doing in the mod.

**Comment by SOMSTATE** [comment]
It's been a while and I almost forgot about this suggestion, I rarely check GitHub.
This is achievable using ContentDisabler now.

**Comment by MeGaGiGaGon** [comment]
Since that’s the case I’ll close this issue. Happy to see someone else did it.
